
export const INVENTORY_MODES = {
  VALVE_ONLY: "VALVE_ONLY",
  COIL_STANDARD_ONLY: "COIL_STANDARD_ONLY",
  COIL_INDEPENDENT_ONLY: "COIL_INDEPENDENT_ONLY",
  VALVE_PLUS_STANDARD: "VALVE_PLUS_STANDARD",
  VALVE_PLUS_INDEPENDENT: "VALVE_PLUS_INDEPENDENT",
};